// My header
// This file has been generated by TauRPC. Do not edit this file manually.
import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult } from '@fltsci/taurpc'
import { ARGS_MAP, RESULT_MAP, TRANSFORM_MAP, type Router } from './bindings'

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP, {
resultMap: RESULT_MAP,
transformMap: TRANSFORM_MAP,
errorHandling: 'result',
})
export type { InferCommandOutput, TauRpcResult }
