use anyhow::{Context, Result, bail};
use heck::ToLowerCamelCase;
use itertools::Itertools;
use specta::TypeCollection;
use specta::datatype::{DataType, Function, FunctionReturnType, Reference};
use specta_typescript as ts;
use specta_typescript::Typescript;
use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fs::{File, OpenOptions};
use std::io::prelude::*;
use std::path::Path;

static PACKAGE_JSON: &str = r#"
{
    "name": ".taurpc",
    "types": "index.ts"
}
"#;

static BOILERPLATE_TS_IMPORT: &str = r#"

import { createTauRPCProxy as createProxy, type InferCommandOutput } from '@fltsci/taurpc'

type TAURI_CHANNEL<T> = (response: T) => void
"#;

static BOILERPLATE_TS_EXPORT: &str = r#"

const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

export {
  type InferCommandOutput,
  createTauRPCProxy
}
"#;

/// Export the generated TS types with the code necessary for generating the client proxy.
///
/// By default, if the `export_to` attribute was not specified on the procedures macro, there will
/// be nothing exported. Otherwise the code will just be export to the .ts file specified by the user.
pub(super) fn export_types(
    export_path: impl AsRef<Path>,
    args_map: BTreeMap<String, String>,
    export_config: ts::Typescript,
    functions: BTreeMap<String, Vec<Function>>,
    type_map: TypeCollection,
) -> Result<()> {
    let path = export_path.as_ref();
    if path.extension() != Some(OsStr::new("ts")) {
        bail!("`export_to` path should be a ts file");
    }

    if let Some(parent) = path.parent() {
        match std::fs::create_dir_all(parent) {
            Ok(_) => (),
            Err(e) => {
                println!("Failed to create directory for exported bindings: {:?}", e);
            }
        }
    }

    let framework_header =
        "// This file has been generated by Specta. Do not edit this file manually.";

    let types = match export_config
        .export(&type_map)
        .context("Failed to generate types with specta")
    {
        Ok(types) => types,
        Err(e) => {
            println!("Failed to generate types with specta: {:?}", e);
            "".to_string()
        }
    };

    // Insert BOILERPLATE_TS_IMPORT right after the framework header,
    // before the type definitions, so the import is always above the types.
    let types = match types.split_once(framework_header) {
        Some((before, after)) => {
            format!("{before}{framework_header}{BOILERPLATE_TS_IMPORT}{after}")
        }
        None => {
            // specta didn't emit the header — prepend header + import ourselves
            format!("{framework_header}{BOILERPLATE_TS_IMPORT}{types}")
        }
    };

    let mut file = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .open(path)
        .context("Cannot open bindings file")?;

    try_write(&mut file, &types);

    let args_entries: String = args_map
        .iter()
        .map(|(k, v)| format!("'{k}':'{v}'"))
        .join(", ");
    let router_args = format!("{{ {args_entries} }}");

    try_write(&mut file, &format!("const ARGS_MAP = {router_args}\n"));
    let functions_router = generate_functions_router(functions, type_map, &export_config);
    try_write(&mut file, &functions_router);
    try_write(&mut file, BOILERPLATE_TS_EXPORT);

    if path
        .to_string_lossy()
        .replace("\\", "/")
        .ends_with("node_modules/.taurpc/index.ts")
    {
        let package_json_path = path
            .parent()
            .map(|path| path.join("package.json"))
            .context("Failed to create 'package.json' path")?;

        std::fs::write(package_json_path, PACKAGE_JSON)
            .context("failed to create 'package.json'")?;
    }

    Ok(())
}

/// Render a DataType as a TypeScript string, preferring named type references
/// over inline definitions when the type is exported.
fn datatype_to_ts(dt: &DataType, export_config: &Typescript, type_map: &TypeCollection) -> String {
    if let DataType::Reference(Reference::Named(r)) = dt {
        if let Some(ndt) = r.get(type_map) {
            if ndt.requires_reference(type_map) {
                let name = ndt.name().to_string();
                if r.generics().is_empty() {
                    return name;
                }
                let generics: Vec<String> = r
                    .generics()
                    .iter()
                    .map(|(_, gdt)| datatype_to_ts(gdt, export_config, type_map))
                    .collect();
                return format!("{}<{}>", name, generics.join(", "));
            }
        }
    }
    ts::primitives::inline(export_config, type_map, dt).unwrap_or_else(|_| "unknown".to_string())
}

/// Recursively replace Named references in a DataType tree with `ts::define(...)`
/// opaques that render as type names instead of inline definitions.
///
/// This handles two cases:
/// - `tauri::ipc::Channel<T>` → `TAURI_CHANNEL<T>` (specta-typescript doesn't
///   support the Channel opaque reference)
/// - Exported types like `User` → `User` (specta marks NamedReferences in function
///   args as inline, but we want type names in the generated signatures)
fn use_type_names(dt: &mut DataType, export_config: &Typescript, type_map: &TypeCollection) {
    match dt {
        DataType::Reference(Reference::Named(r)) => {
            if let Some(ndt) = r.get(type_map) {
                let is_channel =
                    ndt.name() == "TAURI_CHANNEL" && ndt.module_path().starts_with("tauri::");
                if is_channel || ndt.requires_reference(type_map) {
                    let name = if is_channel {
                        "TAURI_CHANNEL".to_string()
                    } else {
                        ndt.name().to_string()
                    };
                    let ts_str = if r.generics().is_empty() {
                        name
                    } else {
                        let generics: Vec<String> = r
                            .generics()
                            .iter()
                            .map(|(_, gdt)| datatype_to_ts(gdt, export_config, type_map))
                            .collect();
                        format!("{}<{}>", name, generics.join(", "))
                    };
                    *dt = DataType::Reference(ts::define(ts_str));
                }
            }
        }
        DataType::Nullable(inner) => use_type_names(inner, export_config, type_map),
        DataType::List(list) => use_type_names(list.ty_mut(), export_config, type_map),
        DataType::Map(map) => {
            use_type_names(map.key_ty_mut(), export_config, type_map);
            use_type_names(map.value_ty_mut(), export_config, type_map);
        }
        DataType::Tuple(tuple) => {
            for element in tuple.elements_mut() {
                use_type_names(element, export_config, type_map);
            }
        }
        _ => {}
    }
}

/// Collapse `Nullable(Tuple([]))` — i.e. `Option<()>` — to just the unit tuple,
/// so it renders as `null` instead of `null | null`.
fn simplify_nullable_unit(dt: &mut DataType) {
    match dt {
        DataType::Nullable(inner) => {
            simplify_nullable_unit(inner);
            if matches!(inner.as_ref(), DataType::Tuple(t) if t.elements().is_empty()) {
                *dt = (**inner).clone();
            }
        }
        DataType::List(list) => simplify_nullable_unit(list.ty_mut()),
        DataType::Map(map) => {
            simplify_nullable_unit(map.key_ty_mut());
            simplify_nullable_unit(map.value_ty_mut());
        }
        DataType::Tuple(tuple) => {
            for element in tuple.elements_mut() {
                simplify_nullable_unit(element);
            }
        }
        _ => {}
    }
}

fn generate_functions_router(
    mut functions: BTreeMap<String, Vec<Function>>,
    type_map: TypeCollection,
    export_config: &Typescript,
) -> String {
    // Preprocess function types before generating TypeScript:
    // - Replace Channel and exported Named references with type name defines
    // - Collapse Option<()> from null | null to null
    for path_functions in functions.values_mut() {
        for function in path_functions.iter_mut() {
            for (_, arg_dt) in function.args_mut() {
                use_type_names(arg_dt, export_config, &type_map);
                simplify_nullable_unit(arg_dt);
            }
            if let Some(ret) = function.result_mut() {
                match ret {
                    FunctionReturnType::Value(dt) | FunctionReturnType::Result(dt, _) => {
                        use_type_names(dt, export_config, &type_map);
                        simplify_nullable_unit(dt);
                    }
                }
            }
        }
    }

    let functions = functions
        .iter()
        .map(|(path, path_functions)| {
            let mut function_names_and_funcs: Vec<_> =
                path_functions.iter().map(|f| (f.name(), f)).collect();
            function_names_and_funcs.sort_by(|a, b| a.0.cmp(b.0));

            let functions = match function_names_and_funcs
                .iter()
                .map(|(_, function)| generate_function(function, export_config, &type_map))
                .collect::<Result<Vec<_>, _>>()
            {
                Ok(functions) => functions.join(", \n"),
                Err(e) => {
                    eprintln!("Error generating functions: {e:?}");
                    "".to_string()
                }
            };

            format!(r#""{path}": {{{functions}}}"#)
        })
        .collect::<Vec<String>>()
        .join(",\n");

    format!("export type Router = {{ {functions} }};\n")
}

fn generate_function(
    function: &Function,
    export_config: &Typescript,
    type_map: &TypeCollection,
) -> Result<String> {
    let args = function
        .args()
        .iter()
        .map(|(name, typ)| {
            ts::primitives::inline(export_config, type_map, typ)
                .map(|ty| format!("{}: {}", name.to_lower_camel_case(), ty))
                .map_err(|e| anyhow::anyhow!(e))
        })
        .collect::<Result<Vec<_>, _>>()
        .context("An error occured while generating command args")?
        .join(", ");

    let return_ty = match function.result() {
        Some(FunctionReturnType::Value(t)) => {
            ts::primitives::inline(export_config, type_map, t).map_err(|e| anyhow::anyhow!(e))?
        }
        // TODO: handle result types
        Some(FunctionReturnType::Result(t, _e)) => {
            ts::primitives::inline(export_config, type_map, t).map_err(|e| anyhow::anyhow!(e))?
        }
        None => "void".to_string(),
    };

    let name = match function.name().split_once("_taurpc_fn__") {
        Some(thing) => thing.1,
        None => return Err(anyhow::anyhow!("Function name is not valid")),
    };

    Ok(format!(r#"{name}: ({args}) => Promise<{return_ty}>"#))
}

fn try_write(file: &mut File, data: &str) {
    match file.write_all(data.as_bytes()) {
        Ok(_) => (),
        Err(e) => {
            eprintln!("Error writing to file: {e:?}");
        }
    };
}
