use heck::ToLowerCamelCase;
use specta::{
    Types,
    datatype::{
        DataType, Field, Fields, Function, NamedReference, NamedReferenceType, Primitive,
        Reference, Struct,
    },
};
use specta_serde::Phase;
use specta_typescript::{Error, Exporter, FrameworkExporter, Typescript, define};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::path::Path;

use crate::{ErrorHandlingMode, ExportRuntimeConfig};

const FRAMEWORK_HEADER: &str =
    "// This file has been generated by TauRPC. Do not edit this file manually.";

static PACKAGE_JSON: &str = r#"
{
    "name": ".taurpc",
    "types": "index.ts",
    "exports": {
        ".": "./index.ts",
        "./proxy": "./proxy.ts"
    }
}
"#;

/// Export the generated TS types and the runtime client proxy.
pub(super) fn export_types(
    export_path: &'static str,
    args_map: BTreeMap<String, String>,
    ts: Typescript,
    functions: BTreeMap<String, Vec<Function>>,
    mut types: Types,
    export_runtime: ExportRuntimeConfig,
) -> Result<(), Error> {
    types.iter_mut(|ndt| {
        if let Some(ty) = ndt.ty.as_mut() {
            rewrite_bigints_in_datatype(ty);
        }
    });

    let exporter: Exporter = ts.into();
    let user_header = exporter.header.clone();

    exporter
        .framework_prelude(FRAMEWORK_HEADER)
        .framework_runtime(move |mut exporter| {
            let mut out = String::new();

            out.push_str(&exporter.render_types()?);

            out.push_str(
                "\nexport type TauRpcResult<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };\n",
            );

            out.push_str("\nexport const ARGS_MAP = ");
            out.push_str(
                &serde_json::to_string_pretty(&args_map)
                    .map_err(|err| Error::framework("error stringify argument map", err))?,
            );
            out.push_str(";\n\n");

            let result_map = generate_result_map(&functions, &exporter);
            out.push_str("export const RESULT_MAP = ");
            out.push_str(
                &serde_json::to_string_pretty(&result_map)
                    .map_err(|err| Error::framework("error stringify result map", err))?,
            );
            out.push_str(";\n\n");

            out.push_str(
                &generate_functions_router(&functions, &exporter, export_runtime.error_handling)
                    .map_err(|err| Error::framework("failed to generate router type", err))?,
            );

            Ok(out.into())
        })
        .export_to(export_path, &types, specta_serde::Format)?;

    let bindings_path = Path::new(export_path);
    let proxy_path = bindings_path.with_file_name("proxy.ts");
    let bindings_stem = bindings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| Error::framework("", "bindings path has no valid file stem"))?;

    write_proxy_file(&proxy_path, bindings_stem, &user_header, &export_runtime)?;

    let normalized = export_path.replace('\\', "/");
    if normalized.ends_with("node_modules/.taurpc/index.ts") {
        let package_json_path = bindings_path
            .parent()
            .ok_or(Error::framework("", "Failed to create 'package.json' path"))?
            .join("package.json");

        std::fs::write(package_json_path, PACKAGE_JSON)
            .map_err(|err| Error::framework("Failed to create 'package.json' file", err))?
    }

    Ok(())
}

fn write_proxy_file(
    proxy_path: &Path,
    bindings_stem: &str,
    user_header: &str,
    export_runtime: &ExportRuntimeConfig,
) -> Result<(), Error> {
    let user_prefix = if user_header.is_empty() {
        String::new()
    } else if user_header.ends_with('\n') {
        user_header.to_string()
    } else {
        format!("{user_header}\n")
    };

    let typed_error_impl = if export_runtime.typed_error_impl.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", export_runtime.typed_error_impl)
    };
    let typed_error_option = if export_runtime.typed_error_impl.is_empty() {
        String::new()
    } else {
        "  typedError,\n".to_string()
    };
    let error_handling = match export_runtime.error_handling {
        ErrorHandlingMode::Throw => "throw",
        ErrorHandlingMode::Result => "result",
    };

    let content = format!(
        "{user_prefix}{FRAMEWORK_HEADER}\n\
         import {{ createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult }} from '@fltsci/taurpc'\n\
         import {{ ARGS_MAP, RESULT_MAP, type Router }} from './{bindings_stem}'\n\n\
         {typed_error_impl}\
         export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP, {{\n\
           resultMap: RESULT_MAP,\n\
           errorHandling: '{error_handling}',\n\
         {typed_error_option}\
         }})\n\
         export type {{ InferCommandOutput, TauRpcResult }}\n"
    );
    std::fs::write(proxy_path, content)
        .map_err(|err| Error::framework("Failed to write proxy.ts", err))?;
    Ok(())
}

fn generate_functions_router(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
    error_handling: ErrorHandlingMode,
) -> Result<String, Error> {
    let mut router = Struct::named();

    for (path, path_functions) in functions {
        let mut function_names_and_funcs: Vec<_> =
            path_functions.iter().map(|f| (f.name(), f)).collect();
        function_names_and_funcs.sort_by(|a, b| a.0.cmp(b.0));

        let mut path_router = Struct::named();
        for (_, function) in function_names_and_funcs {
            let (name, field) = generate_function_field(function, exporter, error_handling)?;
            path_router = path_router.field(name, field);
        }

        router = router.field(path.clone(), Field::new(path_router.build()));
    }

    let router_type = exporter.inline(&router.build())?;
    Ok(format!("export type Router = {router_type};\n"))
}

fn generate_result_map(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
) -> BTreeMap<String, BTreeMap<String, bool>> {
    let mut map = BTreeMap::new();
    for (path, path_functions) in functions {
        let mut route_map = BTreeMap::new();
        for function in path_functions {
            let name = function
                .name()
                .split_once("_taurpc_fn__")
                .map(|(_, name)| name.to_string())
                .unwrap_or_else(|| function.name().to_string());
            route_map.insert(
                name,
                function
                    .result()
                    .is_some_and(|result| extract_std_result(result, exporter.types).is_some()),
            );
        }
        map.insert(path.clone(), route_map);
    }
    map
}

fn generate_function_field(
    function: &Function,
    exporter: &FrameworkExporter,
    error_handling: ErrorHandlingMode,
) -> Result<(String, Field), Error> {
    let args = function
        .args()
        .iter()
        .map(|(name, typ)| {
            render_reference_dt_for_phase(typ, Phase::Deserialize, exporter)
                .map(|ty| format!("{}: {ty}", name.to_lower_camel_case()))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");

    let return_ty = if let Some(result) = function.result() {
        if let Some((ok, err)) = extract_std_result(result, exporter.types) {
            let ok_ty = render_reference_dt_for_phase(ok, Phase::Serialize, exporter)?;
            let err_ty = render_reference_dt_for_phase(err, Phase::Serialize, exporter)?;
            if error_handling == ErrorHandlingMode::Result {
                format!("TauRpcResult<{ok_ty}, {err_ty}>")
            } else {
                ok_ty
            }
        } else {
            render_reference_dt_for_phase(result, Phase::Serialize, exporter)?
        }
    } else {
        "void".to_string()
    };

    let name = function.name().split_once("_taurpc_fn__").unwrap().1;
    Ok((
        name.to_string(),
        Field::new(DataType::Reference(define(format!(
            "({args}) => Promise<{return_ty}>"
        ))))
        .into(),
    ))
}

fn render_reference_dt(dt: &DataType, exporter: &FrameworkExporter) -> Result<String, Error> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = exporter.types.get(r)
        && ndt.name == "TAURI_CHANNEL"
        && ndt.module_path.starts_with("tauri::")
    {
        let generic = if let Some((_, dt)) = named_reference_generics(r).first() {
            match &dt {
                DataType::Reference(r) => exporter.reference(r)?,
                dt => exporter.inline(dt)?,
            }
            .into()
        } else {
            Cow::Borrowed("never")
        };
        Ok(format!("(response: {generic}) => void"))
    } else {
        match &dt {
            DataType::Reference(r) => exporter.reference(r),
            dt => exporter.inline(dt),
        }
    }
}

fn named_reference_generics(r: &NamedReference) -> &[(specta::datatype::Generic, DataType)] {
    match &r.inner {
        NamedReferenceType::Reference { generics, .. } => generics,
        NamedReferenceType::Inline { .. } | NamedReferenceType::Recursive => &[],
    }
}

fn extract_std_result<'a>(
    dt: &'a DataType,
    types: &'a Types,
) -> Option<(&'a DataType, &'a DataType)> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = types.get(r)
        && ndt.name == "Result"
        && (ndt.module_path == "std::result" || ndt.module_path == "core::result")
        && let [(_, ok), (_, err), ..] = named_reference_generics(r)
    {
        return Some((ok, err));
    }

    None
}

fn render_reference_dt_for_phase(
    dt: &DataType,
    phase: Phase,
    exporter: &FrameworkExporter,
) -> Result<String, Error> {
    let dt =
        specta_serde::select_phase_datatype(&rewrite_bigints_for_export(dt), exporter.types, phase);

    render_reference_dt(&dt, exporter)
}

fn rewrite_bigints_for_export(dt: &DataType) -> DataType {
    let mut dt = dt.clone();
    rewrite_bigints_in_datatype(&mut dt);
    dt
}

fn rewrite_bigints_in_datatype(dt: &mut DataType) {
    fn rewrite_bigints_in_fields(fields: &mut Fields) {
        match fields {
            Fields::Unit => {}
            Fields::Unnamed(fields) => {
                for field in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
            Fields::Named(fields) => {
                for (_, field) in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
        }
    }

    match dt {
        DataType::Primitive(primitive) => match primitive {
            Primitive::usize
            | Primitive::isize
            | Primitive::u64
            | Primitive::i64
            | Primitive::u128
            | Primitive::i128
            | Primitive::f128 => *dt = DataType::Primitive(Primitive::f64),
            _ => {}
        },
        DataType::List(list) => rewrite_bigints_in_datatype(&mut list.ty),
        DataType::Map(map) => {
            rewrite_bigints_in_datatype(map.key_ty_mut());
            rewrite_bigints_in_datatype(map.value_ty_mut());
        }
        DataType::Struct(strct) => rewrite_bigints_in_fields(&mut strct.fields),
        DataType::Enum(enm) => {
            for (_, variant) in enm.variants.iter_mut() {
                rewrite_bigints_in_fields(&mut variant.fields);
            }
        }
        DataType::Tuple(tuple) => {
            for item in tuple.elements.iter_mut() {
                rewrite_bigints_in_datatype(item);
            }
        }
        DataType::Nullable(inner) => rewrite_bigints_in_datatype(inner),
        DataType::Reference(Reference::Named(reference)) => {
            if let NamedReferenceType::Reference { generics, .. } = &mut reference.inner {
                for (_, generic) in generics.iter_mut() {
                    rewrite_bigints_in_datatype(generic);
                }
            }
        }
        DataType::Generic(_) | DataType::Reference(Reference::Opaque(_)) => {}
        DataType::Intersection(types) => {
            for ty in types {
                rewrite_bigints_in_datatype(ty);
            }
        }
    }
}
