use heck::ToLowerCamelCase;
use specta::{
    Format, Type, Types,
    datatype::{
        DataType, Field, Fields, Function, NamedReference, NamedReferenceType, Primitive,
        Reference, Struct,
    },
};
use specta_serde::Phase;
use specta_typescript::{Error, Exporter, FrameworkExporter, Typescript, define};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::path::Path;

use crate::{ErrorHandlingMode, ExportRuntimeConfig};

const FRAMEWORK_HEADER: &str =
    "// This file has been generated by TauRPC. Do not edit this file manually.";

static PACKAGE_JSON: &str = r#"
{
    "name": ".taurpc",
    "types": "index.ts",
    "exports": {
        ".": "./index.ts",
        "./proxy": "./proxy.ts"
    }
}
"#;

/// Export the generated TS types and the runtime client proxy.
pub(super) fn export_types(
    export_path: &'static str,
    args_map: BTreeMap<String, String>,
    ts: Typescript,
    functions: BTreeMap<String, Vec<Function>>,
    types: Types,
    export_runtime: ExportRuntimeConfig,
) -> Result<(), Error> {
    let types = hide_unused_std_result_type(&functions, types);
    let exporter: Exporter = ts.into();
    let user_header = exporter.header.clone();
    let runtime_types = format_serde_types(&types, &export_runtime)?;
    let format = TauRpcFormat::new(&export_runtime);
    let export_runtime_for_runtime = export_runtime.clone();

    exporter
        .framework_prelude(FRAMEWORK_HEADER)
        .framework_runtime(move |mut exporter| {
            let mut out = String::new();

            out.push_str(&exporter.render_types()?);

            out.push_str(
                "\nexport type TauRpcResult<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };\n",
            );

            out.push_str("\nexport const ARGS_MAP = ");
            out.push_str(
                &serde_json::to_string_pretty(&args_map)
                    .map_err(|err| Error::framework("error stringify argument map", err))?,
            );
            out.push_str(";\n\n");

            let result_map = generate_result_map(&functions, &exporter);
            out.push_str("export const RESULT_MAP = ");
            out.push_str(
                &serde_json::to_string_pretty(&result_map)
                    .map_err(|err| Error::framework("error stringify result map", err))?,
            );
            out.push_str(";\n\n");

            out.push_str("export const TRANSFORM_MAP = ");
            out.push_str(&generate_transform_map(
                &functions,
                &exporter,
                &runtime_types,
                &export_runtime_for_runtime,
            )?);
            out.push_str(";\n\n");

            out.push_str(
                &generate_functions_router(
                    &functions,
                    &exporter,
                    &runtime_types,
                    &export_runtime_for_runtime,
                )
                .map_err(|err| Error::framework("failed to generate router type", err))?,
            );

            Ok(out.into())
        })
        .export_to(export_path, &types, format)?;

    let bindings_path = Path::new(export_path);
    let proxy_path = bindings_path.with_file_name("proxy.ts");
    let bindings_stem = bindings_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| Error::framework("", "bindings path has no valid file stem"))?;

    write_proxy_file(&proxy_path, bindings_stem, &user_header, &export_runtime)?;

    let normalized = export_path.replace('\\', "/");
    if normalized.ends_with("node_modules/.taurpc/index.ts") {
        let package_json_path = bindings_path
            .parent()
            .ok_or(Error::framework("", "Failed to create 'package.json' path"))?
            .join("package.json");

        std::fs::write(package_json_path, PACKAGE_JSON)
            .map_err(|err| Error::framework("Failed to create 'package.json' file", err))?
    }

    Ok(())
}

fn write_proxy_file(
    proxy_path: &Path,
    bindings_stem: &str,
    user_header: &str,
    export_runtime: &ExportRuntimeConfig,
) -> Result<(), Error> {
    let user_prefix = if user_header.is_empty() {
        String::new()
    } else if user_header.ends_with('\n') {
        user_header.to_string()
    } else {
        format!("{user_header}\n")
    };

    let typed_error_impl = if export_runtime.typed_error_impl.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", export_runtime.typed_error_impl)
    };
    let typed_error_option = if export_runtime.typed_error_impl.is_empty() {
        String::new()
    } else {
        "  typedError,\n".to_string()
    };
    let error_handling = match export_runtime.error_handling {
        ErrorHandlingMode::Throw => "throw",
        ErrorHandlingMode::Result => "result",
    };

    let content = format!(
        "{user_prefix}{FRAMEWORK_HEADER}\n\
         import {{ createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult }} from '@fltsci/taurpc'\n\
         import {{ ARGS_MAP, RESULT_MAP, TRANSFORM_MAP, type Router }} from './{bindings_stem}'\n\n\
         {typed_error_impl}\
         export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP, {{\n\
         \x20\x20resultMap: RESULT_MAP,\n\
         \x20\x20transformMap: TRANSFORM_MAP,\n\
         \x20\x20errorHandling: '{error_handling}',\n\
         {typed_error_option}\
         }})\n\
         export type {{ InferCommandOutput, TauRpcResult }}\n"
    );
    std::fs::write(proxy_path, content)
        .map_err(|err| Error::framework("Failed to write proxy.ts", err))?;
    Ok(())
}

fn generate_functions_router(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
    runtime_types: &Types,
    export_runtime: &ExportRuntimeConfig,
) -> Result<String, Error> {
    let mut router = Struct::named();

    for (path, path_functions) in functions {
        let mut function_names_and_funcs: Vec<_> =
            path_functions.iter().map(|f| (f.name(), f)).collect();
        function_names_and_funcs.sort_by(|a, b| a.0.cmp(b.0));

        let mut path_router = Struct::named();
        for (_, function) in function_names_and_funcs {
            let (name, field) =
                generate_function_field(function, exporter, runtime_types, export_runtime)?;
            path_router = path_router.field(name, field);
        }

        router = router.field(path.clone(), Field::new(path_router.build()));
    }

    let router_type = exporter.inline(&router.build())?;
    Ok(format!("export type Router = {router_type};\n"))
}

fn generate_result_map(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
) -> BTreeMap<String, BTreeMap<String, bool>> {
    let mut map = BTreeMap::new();
    for (path, path_functions) in functions {
        let mut route_map = BTreeMap::new();
        for function in path_functions {
            let name = function
                .name()
                .split_once("_taurpc_fn__")
                .map(|(_, name)| name.to_string())
                .unwrap_or_else(|| function.name().to_string());
            route_map.insert(
                name,
                function
                    .result()
                    .is_some_and(|result| extract_std_result(result, exporter.types).is_some()),
            );
        }
        map.insert(path.clone(), route_map);
    }
    map
}

fn generate_function_field(
    function: &Function,
    exporter: &FrameworkExporter,
    runtime_types: &Types,
    export_runtime: &ExportRuntimeConfig,
) -> Result<(String, Field), Error> {
    let args = function
        .args()
        .iter()
        .map(|(name, typ)| {
            render_reference_dt_for_phase(
                typ,
                Phase::Deserialize,
                Phase::Serialize,
                exporter,
                runtime_types,
                export_runtime,
            )
            .map(|ty| format!("{}: {ty}", name.to_lower_camel_case()))
        })
        .collect::<Result<Vec<_>, _>>()?
        .join(", ");

    let return_ty = if let Some(result) = function.result() {
        if let Some((ok, err)) = extract_std_result(result, exporter.types) {
            let ok_ty = render_reference_dt_for_phase(
                ok,
                Phase::Serialize,
                Phase::Deserialize,
                exporter,
                runtime_types,
                export_runtime,
            )?;
            let err_ty = render_reference_dt_for_phase(
                err,
                Phase::Serialize,
                Phase::Deserialize,
                exporter,
                runtime_types,
                export_runtime,
            )?;
            if export_runtime.error_handling == ErrorHandlingMode::Result {
                format!("TauRpcResult<{ok_ty}, {err_ty}>")
            } else {
                ok_ty
            }
        } else {
            render_reference_dt_for_phase(
                result,
                Phase::Serialize,
                Phase::Deserialize,
                exporter,
                runtime_types,
                export_runtime,
            )?
        }
    } else {
        "void".to_string()
    };

    let name = function.name().split_once("_taurpc_fn__").unwrap().1;
    Ok((
        name.to_string(),
        Field::new(DataType::Reference(define(format!(
            "({args}) => Promise<{return_ty}>"
        )))),
    ))
}

fn render_reference_dt(dt: &DataType, exporter: &FrameworkExporter) -> Result<String, Error> {
    if let Some(r) = tauri_channel_reference(dt, exporter.types) {
        let generic = if let Some((_, dt)) = named_reference_generics(r).first() {
            match &dt {
                DataType::Reference(r) => exporter.reference(r)?,
                dt => exporter.inline(dt)?,
            }
            .into()
        } else {
            Cow::Borrowed("never")
        };
        Ok(format!("(response: {generic}) => void"))
    } else {
        match &dt {
            DataType::Reference(r) => exporter.reference(r),
            dt => exporter.inline(dt),
        }
    }
}

fn tauri_channel_reference<'a>(dt: &'a DataType, types: &'a Types) -> Option<&'a NamedReference> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = types.get(r)
        && ndt.name == "TAURI_CHANNEL"
        && ndt.module_path.starts_with("tauri::")
    {
        Some(r)
    } else {
        None
    }
}

fn named_reference_generics(r: &NamedReference) -> &[(specta::datatype::Generic, DataType)] {
    match &r.inner {
        NamedReferenceType::Reference { generics, .. } => generics,
        NamedReferenceType::Inline { .. } | NamedReferenceType::Recursive(_) => &[],
    }
}

fn extract_std_result<'a>(
    dt: &'a DataType,
    types: &'a Types,
) -> Option<(&'a DataType, &'a DataType)> {
    if let DataType::Reference(Reference::Named(r)) = dt
        && let Some(ndt) = types.get(r)
        && ndt.name == "Result"
        && (ndt.module_path == "std::result" || ndt.module_path == "core::result")
        && let [(_, ok), (_, err), ..] = named_reference_generics(r)
    {
        return Some((ok, err));
    }

    None
}

fn render_reference_dt_for_phase(
    dt: &DataType,
    serde_phase: Phase,
    semantic_phase: Phase,
    exporter: &FrameworkExporter,
    runtime_types: &Types,
    export_runtime: &ExportRuntimeConfig,
) -> Result<String, Error> {
    let mut dt = if export_runtime.disable_serde_phases {
        dt.clone()
    } else {
        specta_serde::select_phase_datatype(dt, exporter.types, serde_phase)
    };

    if let Some(semantic_types) = &export_runtime.semantic_types {
        dt = apply_semantic_type_for_phase(&dt, semantic_phase, "v", runtime_types, semantic_types)
            .and_then(|(dt, _)| dt)
            .unwrap_or(dt);
    }

    if export_runtime.dangerously_cast_bigints_to_number {
        rewrite_bigints_in_datatype(&mut dt);
    }

    render_reference_dt(&dt, exporter)
}

fn apply_semantic_type_for_phase(
    dt: &DataType,
    phase: Phase,
    input: &str,
    types: &Types,
    semantic_types: &specta_typescript::semantic::Configuration,
) -> Option<(Option<DataType>, String)> {
    match phase {
        Phase::Serialize => semantic_types.apply_serialize(types, dt, input),
        Phase::Deserialize => semantic_types.apply_deserialize(types, dt, input),
    }
}

fn generate_transform_map(
    functions: &BTreeMap<String, Vec<Function>>,
    exporter: &FrameworkExporter,
    runtime_types: &Types,
    export_runtime: &ExportRuntimeConfig,
) -> Result<String, Error> {
    let Some(semantic_types) = &export_runtime.semantic_types else {
        return Ok("{}".to_string());
    };

    let mut routes = Vec::new();
    for (path, path_functions) in functions {
        let mut methods = Vec::new();
        for function in path_functions {
            let name = function.name().split_once("_taurpc_fn__").unwrap().1;
            let mut args = Vec::new();
            let mut event_args = Vec::new();
            for (_, arg_dt) in function.args() {
                let transform = if let Some(channel) =
                    tauri_channel_reference(arg_dt, exporter.types)
                    && let Some((_, response_dt)) = named_reference_generics(channel).first()
                {
                    let response_dt = select_dt_for_config(
                        response_dt,
                        Phase::Serialize,
                        exporter.types,
                        export_runtime,
                    );
                    apply_semantic_type_for_phase(
                        &response_dt,
                        Phase::Deserialize,
                        "response",
                        runtime_types,
                        semantic_types,
                    )
                    .map(|(_, runtime)| runtime)
                    .filter(|runtime| runtime != "response")
                    .map(|runtime| {
                        format!(
                            "{{ const transform = (response) => {runtime}; if (typeof v === \"function\") return (response) => v(transform(response)); const onmessage = v.onmessage; v.onmessage = (response) => onmessage(transform(response)); return v }}"
                        )
                    })
                } else {
                    let dt = select_dt_for_config(
                        arg_dt,
                        Phase::Deserialize,
                        exporter.types,
                        export_runtime,
                    );
                    apply_semantic_type_for_phase(
                        &dt,
                        Phase::Serialize,
                        "v",
                        runtime_types,
                        semantic_types,
                    )
                    .map(|(_, runtime)| runtime)
                    .filter(|runtime| runtime != "v")
                };

                args.push(match transform {
                    Some(transform) => format!("(v) => {transform}"),
                    None => "null".to_string(),
                });

                let event_dt =
                    select_dt_for_config(arg_dt, Phase::Serialize, exporter.types, export_runtime);
                let event_transform = apply_semantic_type_for_phase(
                    &event_dt,
                    Phase::Deserialize,
                    "v",
                    runtime_types,
                    semantic_types,
                )
                .map(|(_, runtime)| runtime)
                .filter(|runtime| runtime != "v");

                event_args.push(match event_transform {
                    Some(transform) => format!("(v) => {transform}"),
                    None => "null".to_string(),
                });
            }

            let result = function.result().and_then(|dt| {
                let dt = extract_std_result(dt, exporter.types)
                    .map(|(ok, _)| ok)
                    .unwrap_or(dt);
                let dt = select_dt_for_config(dt, Phase::Serialize, exporter.types, export_runtime);
                apply_semantic_type_for_phase(
                    &dt,
                    Phase::Deserialize,
                    "v",
                    runtime_types,
                    semantic_types,
                )
                .map(|(_, runtime)| runtime)
                .filter(|runtime| runtime != "v")
            });

            if args.iter().any(|arg| arg != "null")
                || event_args.iter().any(|arg| arg != "null")
                || result.is_some()
            {
                let result = result
                    .map(|transform| format!("(v) => {transform}"))
                    .unwrap_or_else(|| "null".to_string());
                methods.push(format!(
                    "{}: {{ args: [{}], eventArgs: [{}], result: {} }}",
                    serde_json::to_string(name)
                        .map_err(|err| Error::framework("error stringify transform name", err))?,
                    args.join(", "),
                    event_args.join(", "),
                    result
                ));
            }
        }

        if !methods.is_empty() {
            routes.push(format!(
                "{}: {{ {} }}",
                serde_json::to_string(path)
                    .map_err(|err| Error::framework("error stringify transform path", err))?,
                methods.join(", ")
            ));
        }
    }

    Ok(format!("{{ {} }}", routes.join(", ")))
}

fn select_dt_for_config(
    dt: &DataType,
    phase: Phase,
    types: &Types,
    export_runtime: &ExportRuntimeConfig,
) -> DataType {
    if export_runtime.disable_serde_phases {
        dt.clone()
    } else {
        specta_serde::select_phase_datatype(dt, types, phase)
    }
}

fn format_serde_types(types: &Types, export_runtime: &ExportRuntimeConfig) -> Result<Types, Error> {
    let types = if export_runtime.disable_serde_phases {
        specta_serde::Format.map_types(types)
    } else {
        specta_serde::PhasesFormat.map_types(types)
    }
    .map_err(|err| Error::framework("failed to format serde types", err))?;

    Ok(types.into_owned())
}

fn hide_unused_std_result_type(
    functions: &BTreeMap<String, Vec<Function>>,
    mut types: Types,
) -> Types {
    let result_is_used = functions.values().flatten().any(|function| {
        function
            .args()
            .iter()
            .any(|(_, dt)| datatype_contains_std_result(dt, &types))
            || function.result().is_some_and(|dt| {
                if let Some((ok, err)) = extract_std_result(dt, &types) {
                    datatype_contains_std_result(ok, &types)
                        || datatype_contains_std_result(err, &types)
                } else {
                    datatype_contains_std_result(dt, &types)
                }
            })
    });

    if result_is_used {
        return types;
    }

    types.iter_mut(|ndt| {
        if is_std_result_ndt(ndt.name.as_ref(), ndt.module_path.as_ref()) {
            ndt.ty = None;
        }
    });

    types
}

fn datatype_contains_std_result(dt: &DataType, types: &Types) -> bool {
    match dt {
        DataType::Reference(Reference::Named(r)) => {
            if let Some(ndt) = types.get(r)
                && is_std_result_ndt(ndt.name.as_ref(), ndt.module_path.as_ref())
            {
                return true;
            }

            named_reference_generics(r)
                .iter()
                .any(|(_, dt)| datatype_contains_std_result(dt, types))
        }
        DataType::List(list) => datatype_contains_std_result(&list.ty, types),
        DataType::Map(map) => {
            datatype_contains_std_result(map.key_ty(), types)
                || datatype_contains_std_result(map.value_ty(), types)
        }
        DataType::Struct(strct) => fields_contain_std_result(&strct.fields, types),
        DataType::Enum(enm) => enm
            .variants
            .iter()
            .any(|(_, variant)| fields_contain_std_result(&variant.fields, types)),
        DataType::Tuple(tuple) => tuple
            .elements
            .iter()
            .any(|dt| datatype_contains_std_result(dt, types)),
        DataType::Nullable(inner) => datatype_contains_std_result(inner, types),
        DataType::Intersection(items) => items
            .iter()
            .any(|dt| datatype_contains_std_result(dt, types)),
        DataType::Primitive(_)
        | DataType::Generic(_)
        | DataType::Reference(Reference::Opaque(_)) => false,
    }
}

fn fields_contain_std_result(fields: &Fields, types: &Types) -> bool {
    match fields {
        Fields::Unit => false,
        Fields::Unnamed(fields) => fields.fields.iter().any(|field| {
            field
                .ty
                .as_ref()
                .is_some_and(|dt| datatype_contains_std_result(dt, types))
        }),
        Fields::Named(fields) => fields.fields.iter().any(|(_, field)| {
            field
                .ty
                .as_ref()
                .is_some_and(|dt| datatype_contains_std_result(dt, types))
        }),
    }
}

fn is_std_result_ndt(name: &str, module_path: &str) -> bool {
    name == "Result"
        && (module_path == "std::result"
            || module_path == "core::result"
            || module_path.contains("result"))
}

#[derive(Debug, Clone)]
struct TauRpcFormat {
    export_runtime: ExportRuntimeConfig,
}

impl TauRpcFormat {
    fn new(export_runtime: &ExportRuntimeConfig) -> Self {
        Self {
            export_runtime: export_runtime.clone(),
        }
    }
}

impl Format for TauRpcFormat {
    fn map_types(&'_ self, types: &Types) -> Result<Cow<'_, Types>, specta::FormatError> {
        let mut types = format_serde_types(types, &self.export_runtime)
            .map_err(|err| Box::new(err) as specta::FormatError)?;

        if let Some(semantic_types) = &self.export_runtime.semantic_types {
            types = semantic_types.apply_types(&types).into_owned();
        }

        if self.export_runtime.dangerously_cast_bigints_to_number {
            types.iter_mut(|ndt| {
                if let Some(ty) = ndt.ty.as_mut() {
                    rewrite_bigints_in_datatype(ty);
                }
            });
        }

        Ok(Cow::Owned(types))
    }

    fn map_type(
        &'_ self,
        types: &Types,
        dt: &DataType,
    ) -> Result<Cow<'_, DataType>, specta::FormatError> {
        let mut dt = if self.export_runtime.disable_serde_phases {
            specta_serde::Format.map_type(types, dt)
        } else {
            specta_serde::PhasesFormat.map_type(types, dt)
        }?;

        if self.export_runtime.dangerously_cast_bigints_to_number {
            let mut owned = dt.into_owned();
            rewrite_bigints_in_datatype(&mut owned);
            dt = Cow::Owned(owned);
        }

        Ok(dt)
    }
}

fn rewrite_bigints_in_datatype(dt: &mut DataType) {
    fn rewrite_bigints_in_fields(fields: &mut Fields) {
        match fields {
            Fields::Unit => {}
            Fields::Unnamed(fields) => {
                for field in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
            Fields::Named(fields) => {
                for (_, field) in fields.fields.iter_mut() {
                    if let Some(ty) = field.ty.as_mut() {
                        rewrite_bigints_in_datatype(ty);
                    }
                }
            }
        }
    }

    if *dt == <specta_typescript::BigInt as Type>::definition(&mut Types::default()) {
        *dt = <specta_typescript::Number as Type>::definition(&mut Types::default());
        return;
    }

    match dt {
        DataType::Primitive(primitive) => match primitive {
            Primitive::usize
            | Primitive::isize
            | Primitive::u64
            | Primitive::i64
            | Primitive::u128
            | Primitive::i128 => {
                *dt = <specta_typescript::Number as Type>::definition(&mut Types::default())
            }
            _ => {}
        },
        DataType::List(list) => rewrite_bigints_in_datatype(&mut list.ty),
        DataType::Map(map) => {
            rewrite_bigints_in_datatype(map.key_ty_mut());
            rewrite_bigints_in_datatype(map.value_ty_mut());
        }
        DataType::Struct(strct) => rewrite_bigints_in_fields(&mut strct.fields),
        DataType::Enum(enm) => {
            for (_, variant) in enm.variants.iter_mut() {
                rewrite_bigints_in_fields(&mut variant.fields);
            }
        }
        DataType::Tuple(tuple) => {
            for item in tuple.elements.iter_mut() {
                rewrite_bigints_in_datatype(item);
            }
        }
        DataType::Nullable(inner) => rewrite_bigints_in_datatype(inner),
        DataType::Reference(Reference::Named(reference)) => {
            if let NamedReferenceType::Reference { generics, .. } = &mut reference.inner {
                for (_, generic) in generics.iter_mut() {
                    rewrite_bigints_in_datatype(generic);
                }
            }
        }
        DataType::Generic(_) | DataType::Reference(Reference::Opaque(_)) => {}
        DataType::Intersection(types) => {
            for ty in types {
                rewrite_bigints_in_datatype(ty);
            }
        }
    }
}
